-- Generated by Ryoku Settings (Super + ,). Lives in the user_edits overlay,
-- overwritten on every change, so change it in the GUI, not by hand. Loaded
-- after Ryoku's defaults and before your user.lua, which still wins.

hl.config({
  general = { border_size = 1 },
  decoration = { blur = { size = 2, contrast = 1.1 } },
  input = { kb_layout = "us", kb_variant = "", kb_options = "", numlock_by_default = true },
})

hl.animation({ leaf = "windowsIn", enabled = true, speed = 3.8, bezier = "ryokuBloom", style = "gnomed" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 2.4, bezier = "ryokuSettle", style = "gnomed" })
hl.curve("dynamic-cursors-magnification", { type = "bezier", points = { { 0.34, 1.5 }, { 0.64, 1.0 } } })
hl.curve("quick", { type = "bezier", points = { { 0.25, 0.1 }, { 0.25, 1.0 } } })

hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "23")
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "23")

hl.env("BROWSER", "zen-browser")

pcall(function()
  hl.plugin.load("/usr/lib/hyprland/plugins/hyprglass.so")
  hl.config({ plugin = { hyprglass = { enabled = 1, default_preset = "glass", blur_strength = 2.0, glass_opacity = 1.0, tint_color = 0x8899aa22, brightness = 1.0, default_theme = "dark" } } })
end)


hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl setcursor Bibata-Modern-Ice 23")
end)
